# provision.yml

- name: Provision machine
  hosts: "all"
  become: true
  
  roles:
    - role: "nickjj.docker"
      tags: ["docker"]
      vars:
        docker__edition: "ce"
        docker__channel: ["stable"]
        docker__version: "20.10.14"

  post_tasks:
    - name: apt install compose plugin
      apt: 
        pkg:
          - docker-compose-plugin

    - name: Docker info
      shell: docker info


